### ISSUE TITLE
go350.com is not compromised

### ISSUE THREAD

**Issue by ghost** [pan-unit42/iocs#7]
I own the domain go350.com. It's not compromised or malicious in any way. Would you please remove it from this list? I have full control of the domain, its DNS, etc.

**Comment by jgrunzweig** [comment]
Hello w8rbt,

Where exactly are you seeing this domain listed within the iocs repository? A cursory search for it yielded no results on my end.

Thanks

**Comment by ghost** [comment]
This URL specifically... https://raw.githubusercontent.com/pan-unit42/iocs/master/angler/compromised_domains

**Comment by ghost** [comment]
Also, that file 'iocs/angler/compromised_domains' was committed 3 years ago. There are probably many other inaccuracies and errors in it today as well. A lot changes in that amount of time.

**Comment by jgrunzweig** [comment]
Per your request, I've removed the domain in question. I agree with your statement about how a number of these domains may have changed in the time since this file was uploaded. However, to that point, it's important to remember that we're not claiming that these domains are currently compromised. Rather, at the time of publication (~3 years ago), there was evidence to associate these domains with the Angler Exploit Kit.
